version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: elevenlabs
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: